# Generated by Django 5.2.15 on 2026-06-14 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('people', '0002_alter_person_options_person_do_not_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('text', 'Text'), ('meeting', 'Meeting'), ('voicemail', 'Voicemail'), ('facebook_message', 'Facebook Message'), ('website_inquiry', 'Website Inquiry'), ('referral_note', 'Referral Note'), ('other', 'Other')], max_length=100)),
                ('communication_date', models.DateField()),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField()),
                ('outcome', models.CharField(blank=True, choices=[('connected', 'Connected'), ('left_message', 'Left Message'), ('no_response', 'No Response'), ('scheduled_consult', 'Scheduled Consult'), ('sent_info', 'Sent Information'), ('follow_up_needed', 'Follow-Up Needed'), ('not_interested', 'Not Interested'), ('converted', 'Converted'), ('other', 'Other')], max_length=100)),
                ('next_step', models.CharField(blank=True, max_length=255)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.lead')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
            ],
        ),
    ]
