# Generated by Django 5.2.15 on 2026-06-14 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('people', '0002_alter_person_options_person_do_not_contact_and_more'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['next_follow_up_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='lead',
            name='next_step',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_leads', to='people.person'),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('property_management', 'Property Management'), ('home_management', 'Home Management'), ('flat_fee_listing', 'Flat-Fee Listing'), ('investor', 'Investor'), ('referral', 'Referral'), ('probate_estate', 'Probate / Estate'), ('downsizing', 'Downsizing'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='people.person'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='related_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='properties.property'),
        ),
    ]
