# Generated by Django 5.2.15 on 2026-06-12 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('buyer_representation', 'Buyer Representation'), ('seller_representation', 'Seller Representation'), ('property_management', 'Property Management'), ('home_management', 'Home Management'), ('flat_fee_listing', 'Flat-Fee Listing'), ('vacant_property_watch', 'Vacant Property Watch'), ('repair_coordination', 'Repair Coordination')], max_length=100)),
                ('status', models.CharField(choices=[('inquiry', 'Inquiry'), ('proposal_sent', 'Proposal Sent'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='inquiry', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property')),
            ],
        ),
    ]
