# Generated by Django 5.2.15 on 2026-06-12 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('contract', 'Contract'), ('listing_agreement', 'Listing Agreement'), ('disclosure', 'Disclosure'), ('inspection_report', 'Inspection Report'), ('photo', 'Photo'), ('invoice', 'Invoice'), ('repair_photo', 'Repair Photo'), ('home_management_report', 'Home Management Report'), ('property_management_report', 'Property Management Report'), ('other', 'Other')], default='other', max_length=100)),
                ('file', models.FileField(upload_to='documents/')),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('related_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.person')),
                ('related_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property')),
            ],
        ),
    ]
