# Generated by Django 5.2.15 on 2026-06-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('person_type', models.CharField(choices=[('lead', 'Lead'), ('buyer', 'Buyer'), ('seller', 'Seller'), ('owner', 'Owner'), ('tenant', 'Tenant'), ('vendor', 'Vendor'), ('agent', 'Agent'), ('attorney', 'Attorney'), ('lender', 'Lender'), ('family_contact', 'Family Contact')], default='lead', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
