# Generated by Django 5.2.15 on 2026-06-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='person',
            name='do_not_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='email_opt_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='preferred_contact_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('text', 'Text'), ('facebook', 'Facebook Message'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='sms_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('lead', 'Lead'), ('buyer', 'Buyer'), ('seller', 'Seller'), ('owner', 'Owner'), ('tenant', 'Tenant'), ('vendor', 'Vendor'), ('agent', 'Agent'), ('attorney', 'Attorney'), ('lender', 'Lender'), ('family_contact', 'Family Contact'), ('referral_partner', 'Referral Partner'), ('other', 'Other')], default='lead', max_length=50),
        ),
    ]
