# Generated by Django 5.2.15 on 2026-06-15 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0002_alter_lead_options_lead_next_step_lead_referred_by_and_more'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('campaign_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('phone', 'Phone Call'), ('mail', 'Direct Mail'), ('social', 'Social Media'), ('other', 'Other')], default='email', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('audience_built', 'Audience Built'), ('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='draft', max_length=50)),
                ('audience_lead_type', models.CharField(blank=True, max_length=100)),
                ('audience_lead_status', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audience_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('responded', 'Responded'), ('not_interested', 'Not Interested'), ('converted', 'Converted'), ('removed', 'Removed')], default='queued', max_length=50)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='campaigns.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_members', to='leads.lead')),
            ],
            options={
                'ordering': ['lead__person__last_name', 'lead__person__first_name'],
                'unique_together': {('campaign', 'lead')},
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='leads',
            field=models.ManyToManyField(blank=True, related_name='campaigns', through='campaigns.CampaignMember', to='leads.lead'),
        ),
    ]
