# Generated by Django 5.2.15 on 2026-06-12 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('routine', 'Routine'), ('seasonal', 'Seasonal'), ('move_in', 'Move-In'), ('move_out', 'Move-Out'), ('emergency', 'Emergency')], default='routine', max_length=50)),
                ('inspection_date', models.DateField()),
                ('exterior_notes', models.TextField(blank=True)),
                ('interior_notes', models.TextField(blank=True)),
                ('safety_concerns', models.TextField(blank=True)),
                ('maintenance_needed', models.TextField(blank=True)),
                ('follow_up_needed', models.BooleanField(default=False)),
                ('next_inspection_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
        ),
    ]
